[window]
padding = { x = 10, y = 10 }
dynamic_title = true

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors.primary]
background = "#11111b"
foreground = "#cdd6f4"
